import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import { cookieToInitialState } from 'wagmi'

import { headers } from "next/headers";
import { WagmiContextProvider } from "@/contexts/wagmi";
import { config } from "@/wagmi.config";

const fontSans = Plus_Jakarta_Sans({ subsets: ["latin"], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "VoiceDeck II",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
			>
				<WagmiContextProvider initialState={initialState}>
				{children}
				</WagmiContextProvider></body>
    </html>
  );
}
